###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
add_module_names = False
author = 'Kam Kasravi'
bibtex_bibfiles = ['references.bib']
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2022'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
execution_allow_errors = False
execution_excludepatterns = []
execution_in_temp = False
execution_timeout = 30
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_panels', 'sphinx_book_theme', 'sphinx_click.ext', 'sphinx_inline_tabs', 'sphinx.ext.autodoc', 'sphinx.ext.autosummary', 'sphinx.ext.napoleon', 'sphinx.ext.viewcode', 'sphinxcontrib.mermaid', 'sphinxcontrib_autodocgen', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_favicon = ''
html_logo = 'logo.png'
html_sourcelink_suffix = ''
html_theme = 'sphinx_book_theme'
html_theme_options = {'search_bar_text': 'Search this book...', 'launch_buttons': {'notebook_interface': 'classic', 'binderhub_url': 'https://mybinder.org', 'jupyterhub_url': '', 'thebe': False, 'colab_url': ''}, 'path_to_docs': 'docs', 'repository_url': 'https://github.com/kkasravi/explainable-ai-tooling', 'repository_branch': 'main', 'google_analytics_id': '', 'extra_navbar': 'Powered by <a href="https://jupyterbook.org">Jupyter Book</a>', 'extra_footer': '', 'home_page_in_toc': True, 'use_repository_button': True, 'use_edit_page_button': False, 'use_issues_button': True}
html_title = 'Explainer'
intersphinx_mapping = {'ebp': ['https://executablebooks.org/en/latest/', None], 'myst-parser': ['https://myst-parser.readthedocs.io/en/latest/', None], 'myst-nb': ['https://myst-nb.readthedocs.io/en/latest/', None], 'sphinx': ['https://www.sphinx-doc.org/en/master', None], 'nbformat': ['https://nbformat.readthedocs.io/en/latest', None]}
jupyter_cache = ''
jupyter_execute_notebooks = 'force'
language = 'en'
latex_engine = 'pdflatex'
myst_enable_extensions = ['deflist', 'colon_fence', 'linkify', 'substitution', 'tasklist']
myst_substitutions = {'AutoClasses': '<a href="https://huggingface.co/docs/transformers/main/en/model_doc/auto#auto-classes" target="_blank">AutoClasses</a>', 'Glue': '<a href="http://docs.glueviz.org/en/stable" target="_blank">Glue</a>', 'Captum': '<a href="https://captum.ai/" target="_blank">Captum</a>', 'PathExplain': '<a href="https://github.com/suinleelab/path_explain" target="_blank"><i class="fa fa-external-link-alt"></i></a>', 'PyYaml': '<a href="https://matthewpburruss.com/post/yaml/" target="_blank">PyYaml</a>', 'Transformers': '<a href="https://huggingface.co/docs/transformers/index" target="_blank">Transformers</a>', 'TransformersInterpret': '<a href="https://github.com/cdpierse/transformers-interpret" target="_blank"><i class="fa fa-external-link-alt"></i></a>', 'DICEExample': '<a href="https://matthewpburruss.com/post/yaml/" target="_blank">PyYaml</a>', 'YANG202229': '<a href="https://www.sciencedirect.com/science/article/pii/S1566253521001597" target="_blank">Unbox the black-box for the medical explainable AI via multi-modal and multi-centre data fusion&colon; A mini-review, two showcases and beyond</a> {cite}`YANG202229`', 'ZHU202253': '<a href="https://www.sciencedirect.com/science/article/pii/S1566253521001548" target="_blank">Interpretable learning based Dynamic Graph Convolutional Networks for Alzheimer’s Disease analysis</a> {cite}`ZHU202253`', 'HOLZINGER202128': '<a href="https://www.sciencedirect.com/science/article/pii/S1566253521000142" target="_blank">Towards multi-modal causability with Graph Neural Networks enabling information fusion for explainable AI</a> {cite}`ZHU202253`'}
myst_url_schemes = ['mailto', 'http', 'https']
nb_output_stderr = 'show'
numfig = True
panels_add_bootstrap_css = False
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True
