#!/bin/bash
usage()
{
cat << EOF
usage: $0 options
Greps for files with the given pattern
OPTIONS:
   -h      Show this message
   -v      Verbose 
   -d      directory to search recursively in
   -e      exclude directory
   -i      ignorecase
   -t      file pattern regex to search 
   -+      show contents (default is false)
EOF
}
FILEREGEX=""
DIRECTORY=( '*' )
SHOWCONTENTS="l"
IGNORECASE=""
IGNOREBINARY="I"
ARGS=""
while getopts “hivt:p:d:e:+” OPTION
do
     case "${OPTION}" in
         h)
             usage
             exit 1
             ;;
         t)
             FILEREGEX="-name '"$OPTARG"'"
             ;;
         i)
             IGNORECASE=i
             ;;
         +)
             SHOWCONTENTS="H"
             ;;
         d)
             DIRECTORY=( "$OPTARG" )
             ;;
         e)
             EXCLUDE=( "$OPTARG" )
             DIRECTORY=( $(echo $(find ${DIRECTORY[@]} -depth 0 -type d)) )
             DIRECTORY=( "${DIRECTORY[@]/$EXCLUDE}" )
             ;;
         v)
             VERBOSE=true
             ;;
         ?)
             usage
             exit
             ;;
     esac
done
shift $((OPTIND-1))
if [ $# = 0 ]; then
  usage
  exit 1
fi
if [ ${SHOWCONTENTS}${IGNORECASE} != "" ]; then
  ARGS=-${SHOWCONTENTS}${IGNORECASE}${IGNOREBINARY}
else
  ARGS=-${IGNOREBINARY}
fi
if [ ! -z $VERBOSE ]; then
  echo find $(eval echo ${DIRECTORY[@]}) -type f $FILEREGEX -exec grep $ARGS "$1" {} \; 
fi
find $(eval echo ${DIRECTORY[@]}) -type f $FILEREGEX -exec grep $ARGS "$1" {} \; 
